apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 6.42.0
  values:
    # Deine spezifischen Grafana-Werte
    grafana:
      adminPassword: 'admin'
      persistence:
        enabled: false

